/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/myhome.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/myhome.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[2.914, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038}>
        <mesh geometry={nodes.Sample_Book015_1.geometry} material={materials.cover} />
        <mesh geometry={nodes.Sample_Book015_2.geometry} material={materials.wall} />
        <mesh geometry={nodes.Sample_Book015_3.geometry} material={materials.wood} />
        <mesh geometry={nodes.Sample_Book015_4.geometry} material={materials.desk} />
        <mesh geometry={nodes.Sample_Book015_5.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Sample_Book015_6.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Sample_Book015_7.geometry} material={materials.polySurface43SG} />
        <mesh geometry={nodes.Sample_Book015_8.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Sample_Book015_9.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Sample_Book015_10.geometry} material={materials.back} />
        <mesh geometry={nodes.Sample_Book015_11.geometry} material={materials.roll} />
        <mesh geometry={nodes.Sample_Book015_12.geometry} material={materials.Outline} />
        <mesh geometry={nodes.Sample_Book015_13.geometry} material={materials.Screen} />
        <mesh geometry={nodes.Sample_Book015_14.geometry} material={materials.Emission} />
        <mesh geometry={nodes.Sample_Book015_15.geometry} material={materials.Logo} />
        <mesh geometry={nodes.Sample_Book015_16.geometry} material={materials.Main} />
        <mesh geometry={nodes.Sample_Book015_17.geometry} material={materials.Text} />
        <mesh geometry={nodes.Sample_Book015_18.geometry} material={materials.Camera} />
        <mesh geometry={nodes.Sample_Book015_19.geometry} material={materials.Camera1} />
        <mesh geometry={nodes.Sample_Book015_20.geometry} material={materials.CameraGreen} />
        <mesh geometry={nodes.Sample_Book015_21.geometry} material={materials.Black} />
        <mesh geometry={nodes.Sample_Book015_22.geometry} material={materials.Second} />
        <mesh geometry={nodes.Sample_Book015_23.geometry} material={materials.KeysMain} />
        <mesh geometry={nodes.Sample_Book015_24.geometry} material={materials.KeysBottom} />
        <mesh geometry={nodes.Sample_Book015_25.geometry} material={materials.TopLine} />
        <mesh geometry={nodes.Sample_Book015_26.geometry} material={materials.DarkGrey} />
        <mesh geometry={nodes.Sample_Book015_27.geometry} material={materials.cat} />
        <mesh geometry={nodes.Sample_Book015_28.geometry} material={materials.page} />
        <mesh geometry={nodes.Sample_Book015_29.geometry} material={materials.cup} />
        <mesh geometry={nodes.Sample_Book015_30.geometry} material={materials.pang} />
        <mesh geometry={nodes.Sample_Book015_31.geometry} material={materials.Pages} />
        <mesh geometry={nodes.Sample_Book015_32.geometry} material={materials.Title} />
        <mesh geometry={nodes.Sample_Book015_33.geometry} material={materials.Book_4} />
        <mesh geometry={nodes.Sample_Book015_34.geometry} material={materials.Book_1} />
        <mesh geometry={nodes.Sample_Book015_35.geometry} material={materials.Book_2} />
        <mesh geometry={nodes.Sample_Book015_36.geometry} material={materials.Book_3} />
      </group>
    </group>
  )
}

useGLTF.preload('/myhome.glb')
