/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/office.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/office.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.139, 2.218, -1.778]} rotation={[Math.PI / 2, 1.26, Math.PI / 2]} scale={0.084}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials.Pages} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials.Title} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={materials.Book_4} />
        <mesh geometry={nodes.Cylinder004_3.geometry} material={materials.Book_1} />
        <mesh geometry={nodes.Cylinder004_4.geometry} material={materials.Book_2} />
        <mesh geometry={nodes.Cylinder004_5.geometry} material={materials.Book_3} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials.wall} position={[0, 0.001, 0]} scale={[3.991, 0.11, 2.275]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.wood} position={[0.57, -2.589, -2.154]} scale={[7.897, 0.145, 0.419]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.desk} position={[-0.726, 1.929, -1.31]} rotation={[-Math.PI, 0, 0]} scale={[-1.853, -0.087, -0.719]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.leg} position={[-2.322, 0.636, -0.775]} scale={[0.085, 0.702, 0.085]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.leg} position={[-2.322, 0.636, -1.798]} scale={[0.085, 0.702, 0.085]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.leg} position={[0.872, 0.636, -0.775]} scale={[0.085, 0.702, 0.085]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.leg} position={[0.872, 0.636, -1.798]} scale={[0.085, 0.702, 0.085]} />
      <mesh geometry={nodes.Sansevieria.geometry} material={materials['Material.005']} position={[-3.165, 0.186, -1.214]} rotation={[Math.PI / 2, 0, 0]} scale={0.035} />
      <mesh geometry={nodes.Cube006.geometry} material={materials.wood} position={[2.679, 1.483, -1.732]} rotation={[0, 0, -Math.PI]} scale={[-0.927, -0.042, -0.338]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.wood} position={[2.679, 2.161, -1.732]} rotation={[0, 0, -Math.PI]} scale={[-0.927, -0.042, -0.338]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials.wood} position={[2.679, 2.928, -1.732]} rotation={[0, 0, -Math.PI]} scale={[-0.927, -0.042, -0.338]} />
      <mesh geometry={nodes.Sansevieria002.geometry} material={materials['Material.002']} position={[-3.165, 0.186, -1.214]} rotation={[Math.PI / 2, 0, 0]} scale={0.035} />
      <mesh geometry={nodes.Sansevieria001.geometry} material={materials.polySurface43SG} position={[-3.165, 0.186, -1.214]} rotation={[Math.PI / 2, 0, 0]} scale={0.035} />
      <mesh geometry={nodes.Sansevieria018.geometry} material={materials['Material.003']} position={[-3.165, 0.186, -1.214]} rotation={[Math.PI / 2, 0, 0]} scale={0.035} />
      <mesh geometry={nodes.Sansevieria004.geometry} material={materials['Material.004']} position={[-3.165, 0.186, -1.214]} rotation={[Math.PI / 2, 0, 0]} scale={0.035} />
      <mesh geometry={nodes.chair_f002.geometry} material={materials.roll} position={[-0.915, 0.189, 0.309]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.021} />
      <group position={[-0.99, 1.836, -1.857]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.279}>
        <mesh geometry={nodes.macBook_TopPart_Cube004_1.geometry} material={materials.Outline} />
        <mesh geometry={nodes.macBook_TopPart_Cube004_2.geometry} material={materials.Screen} />
        <mesh geometry={nodes.macBook_TopPart_Cube004_3.geometry} material={materials.Emission} />
        <mesh geometry={nodes.macBook_TopPart_Cube004_4.geometry} material={materials.Logo} />
        <mesh geometry={nodes.macBook_TopPart_Cube004_5.geometry} material={materials.Main} />
        <mesh geometry={nodes.macBook_TopPart_Cube004_6.geometry} material={materials.Text} />
        <mesh geometry={nodes.macBook_TopPart_Cube004_7.geometry} material={materials.Camera} />
        <mesh geometry={nodes.macBook_TopPart_Cube004_8.geometry} material={materials.Camera1} />
        <mesh geometry={nodes.macBook_TopPart_Cube004_9.geometry} material={materials.CameraGreen} />
        <mesh geometry={nodes.macBook_TopPart_Cube004_10.geometry} material={materials.Black} />
        <mesh geometry={nodes.macBook_TopPart_Cube004_11.geometry} material={materials.Second} />
        <mesh geometry={nodes.macBook_TopPart_Cube004_12.geometry} material={materials.KeysMain} />
        <mesh geometry={nodes.macBook_TopPart_Cube004_13.geometry} material={materials.KeysBottom} />
        <mesh geometry={nodes.macBook_TopPart_Cube004_14.geometry} material={materials.TopLine} />
        <mesh geometry={nodes.macBook_TopPart_Cube004_15.geometry} material={materials.DarkGrey} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials.floor} position={[0, -0.146, 0]} scale={[3.991, 0.11, 2.275]} />
      <mesh geometry={nodes.ORIGAMI_Chat.geometry} material={materials.cat} position={[0.351, 2.012, -2.177]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.021} />
      <group position={[2.152, 1.526, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]}>
        <mesh geometry={nodes.Sample_Book002_1.geometry} material={materials.page} />
        <mesh geometry={nodes.Sample_Book002_2.geometry} material={materials.cover} />
      </group>
      <group position={[2.207, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038}>
        <mesh geometry={nodes.Sample_Book003_1.geometry} material={materials.page} />
        <mesh geometry={nodes.Sample_Book003_2.geometry} material={materials.cover} />
      </group>
      <group position={[2.593, 2.205, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]}>
        <mesh geometry={nodes.Sample_Book004_1.geometry} material={materials.page} />
        <mesh geometry={nodes.Sample_Book004_2.geometry} material={materials.cover} />
      </group>
      <group position={[2.839, 2.976, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]}>
        <mesh geometry={nodes.Sample_Book005_1.geometry} material={materials.page} />
        <mesh geometry={nodes.Sample_Book005_2.geometry} material={materials.cover} />
      </group>
      <group position={[2.134, 2.978, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]}>
        <mesh geometry={nodes.Sample_Book006_1.geometry} material={materials.page} />
        <mesh geometry={nodes.Sample_Book006_2.geometry} material={materials.cover} />
      </group>
      <group position={[2.92, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038}>
        <mesh geometry={nodes.Sample_Book007_1.geometry} material={materials.page} />
        <mesh geometry={nodes.Sample_Book007_2.geometry} material={materials.cover} />
      </group>
      <group position={[2.912, 2.206, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={0.038}>
        <mesh geometry={nodes.Sample_Book008_1.geometry} material={materials.page} />
        <mesh geometry={nodes.Sample_Book008_2.geometry} material={materials.cover} />
      </group>
      <group position={[2.994, 2.205, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]}>
        <mesh geometry={nodes.Sample_Book009_1.geometry} material={materials.page} />
        <mesh geometry={nodes.Sample_Book009_2.geometry} material={materials.cover} />
      </group>
      <group position={[3.311, 2.205, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]}>
        <mesh geometry={nodes.Sample_Book010_1.geometry} material={materials.page} />
        <mesh geometry={nodes.Sample_Book010_2.geometry} material={materials.cover} />
      </group>
      <mesh geometry={nodes.Sample_Book011.geometry} material={materials.cover} position={[2.914, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
      <mesh geometry={nodes.Sample_Book012.geometry} material={materials.cover} position={[2.914, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
      <mesh geometry={nodes.Sample_Book013.geometry} material={materials.cover} position={[2.914, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
      <mesh geometry={nodes.Sample_Book014.geometry} material={materials.cover} position={[2.914, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
      <mesh geometry={nodes.Sample_Book015.geometry} material={materials.cover} position={[2.914, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
      <mesh geometry={nodes.Sample_Book016.geometry} material={materials.cover} position={[2.914, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
      <mesh geometry={nodes.Sample_Book017.geometry} material={materials.cover} position={[2.914, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
      <mesh geometry={nodes.Sample_Book018.geometry} material={materials.cover} position={[2.914, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
      <mesh geometry={nodes.Sample_Book019.geometry} material={materials.cover} position={[2.213, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
      <mesh geometry={nodes.Sample_Book020.geometry} material={materials.cover} position={[2.213, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
      <mesh geometry={nodes.Sample_Book021.geometry} material={materials.cover} position={[2.213, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
      <mesh geometry={nodes.Sample_Book022.geometry} material={materials.cover} position={[2.213, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
      <mesh geometry={nodes.Sample_Book023.geometry} material={materials.cover} position={[2.213, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
      <mesh geometry={nodes.Sample_Book024.geometry} material={materials.cover} position={[2.213, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
      <mesh geometry={nodes.Sample_Book025.geometry} material={materials.cover} position={[2.213, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
      <mesh geometry={nodes.Sample_Book026.geometry} material={materials.cover} position={[2.213, 2.975, -1.782]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
      <mesh geometry={nodes.Sample_Book027.geometry} material={materials.cover} position={[3.311, 2.205, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book028.geometry} material={materials.cover} position={[3.311, 2.205, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book029.geometry} material={materials.cover} position={[3.311, 2.205, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book030.geometry} material={materials.cover} position={[3.311, 2.205, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book031.geometry} material={materials.cover} position={[2.994, 2.205, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book032.geometry} material={materials.cover} position={[2.994, 2.205, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book033.geometry} material={materials.cover} position={[2.994, 2.205, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book034.geometry} material={materials.cover} position={[2.994, 2.205, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book035.geometry} material={materials.cover} position={[2.593, 2.205, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book036.geometry} material={materials.cover} position={[2.593, 2.205, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book037.geometry} material={materials.cover} position={[2.593, 2.205, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book038.geometry} material={materials.cover} position={[2.593, 2.205, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book039.geometry} material={materials.cover} position={[2.593, 2.205, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book040.geometry} material={materials.cover} position={[2.593, 2.205, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book041.geometry} material={materials.cover} position={[2.593, 2.205, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book001.geometry} material={materials.cover} position={[2.152, 1.526, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book042.geometry} material={materials.cover} position={[2.152, 1.526, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book043.geometry} material={materials.cover} position={[2.152, 1.526, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book044.geometry} material={materials.cover} position={[2.152, 1.526, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book045.geometry} material={materials.cover} position={[2.152, 1.526, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book046.geometry} material={materials.cover} position={[2.152, 1.526, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book047.geometry} material={materials.cover} position={[2.152, 1.526, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book048.geometry} material={materials.cover} position={[2.152, 1.526, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book049.geometry} material={materials.cover} position={[2.152, 1.526, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book050.geometry} material={materials.cover} position={[2.152, 1.526, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book051.geometry} material={materials.cover} position={[2.152, 1.526, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Sample_Book052.geometry} material={materials.cover} position={[2.152, 1.526, -1.781]} rotation={[Math.PI / 2, 0, 0]} scale={[0.038, 0.038, 0.025]} />
      <mesh geometry={nodes.Mug_no_texture.geometry} material={materials.cup} position={[0.295, 2.016, -0.981]} rotation={[Math.PI, 0, Math.PI]} scale={0.001} />
      <mesh geometry={nodes.catjun.geometry} material={materials.pang} position={[-2.165, -12.701, -1.622]} rotation={[Math.PI / 2, 0, -2.286]} scale={0.041} />
      <mesh geometry={nodes.chair_f001.geometry} material={materials.back} position={[-0.915, 0.189, 0.309]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.021} />
      <mesh geometry={nodes.chair_f003.geometry} material={materials.back} position={[-0.915, 0.189, 0.309]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.021} />
    </group>
  )
}

useGLTF.preload('/office.gltf')
